language: csharp
solution: Source/SharpAESCrypt.sln
dotnet: 2.0.0
install:
  - dotnet restore Source/SharpAESCrypt.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
script:
  - dotnet build -c Release Source/SharpAESCrypt.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Unittest/bin/Release/netstandard2.0/Unittest.dll --where:cat==Bulk
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Unittest/bin/Release/netstandard2.0/Unittest.dll --where:cat!=Bulk
